sudo: required

services:
  - docker

before_install:
  - docker build -t bornleo/docker-react-training -f Dockerfile.dev .

script:
  - docker run -e CI=true bornleo/docker-react-training npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-235549775944"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"